"""empty message

Revision ID: 1c1376a5c639
Revises: 1b6fef306c59
Create Date: 2019-03-09 15:03:26.049611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1376a5c639'
down_revision = '1b6fef306c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=3000), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['single_lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('single_lesson', sa.Column('rating', sa.Float(precision=1), nullable=True))
    op.add_column('single_lesson', sa.Column('rating_sum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_lesson', 'rating_sum')
    op.drop_column('single_lesson', 'rating')
    op.drop_table('lesson_comment')
    # ### end Alembic commands ###
