"""empty message

Revision ID: a6114ff69c5d
Revises: 
Create Date: 2019-03-01 15:21:21.285862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6114ff69c5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_tags_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=600), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('about_channel', sa.Text(length=3000), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('video_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interests_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('single_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sa.String(length=256), nullable=True),
    sa.Column('preview', sa.LargeBinary(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('about_lesson', sa.String(length=3000), nullable=True),
    sa.Column('extra_material', sa.String(length=5000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video_lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_channel',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meta_tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meta_tags_id'], ['meta_tags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('attached_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['single_lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_lesson',
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('meta_tag_lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['single_lesson.id'], ),
    sa.ForeignKeyConstraint(['meta_tag_lesson_id'], ['meta_tags_lesson.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_lesson')
    op.drop_table('attached_file')
    op.drop_table('tags_channel')
    op.drop_table('single_lesson')
    op.drop_table('interests_user')
    op.drop_table('video_lesson')
    op.drop_table('user')
    op.drop_table('meta_tags_lesson')
    op.drop_table('meta_tags')
    op.drop_table('interests')
    # ### end Alembic commands ###
