"""empty message

Revision ID: ef62f14a31e6
Revises: a6114ff69c5d
Create Date: 2019-03-05 17:00:26.446753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef62f14a31e6'
down_revision = 'a6114ff69c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers_channel',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.add_column('user', sa.Column('channel_head', sa.LargeBinary(), nullable=True))
    op.add_column('video_lesson', sa.Column('duration', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_lesson', 'duration')
    op.drop_column('user', 'channel_head')
    op.drop_table('subscribers_channel')
    # ### end Alembic commands ###
